### ISSUE TITLE
Configuration options for mapping framwork entities

### ISSUE THREAD

**Issue by fprochazka** [Kdyby/Boilerplate#17]
```
kdyby:
    entities: FALSE
```

or 

```
kdyby:
    entities:
        acl: TRUE
        security: FALSE
        domain: FALSE
        media: TRUE
```

etc...
